<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

function nrb_televie_node_presave($node) {
  if ($node->type == 'event') {
    if ($node->field_groupement['und'][0]['value'] == '') {
      $node->field_groupement['und'][0]['value'] = $node->changed;
    }
  }
}

function nrb_televie_cron() {
//  $dom = new DOMDocument();
//  $dom->load('http://www.rtl.be/televie/rss/events.xml');
//  watchdog('nrb_televie (cron)',"Flux des events téléchargé");
//  $dom->save('rss/events.xml');
//  watchdog('nrb_televie (cron)',"Flux des events sauvé");
//  unset($dom);
}