<?php
/**
 * @file
 * menu_televie_footer.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function menu_televie_footer_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-menu-televie-footer_a-propos-du-tlvie:node/891.
  $menu_links['menu-menu-televie-footer_a-propos-du-tlvie:node/891'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'node/891',
    'router_path' => 'node/%',
    'link_title' => 'A propos du Télévie',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_a-propos-du-tlvie:node/891',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_accueil:<front>.
  $menu_links['menu-menu-televie-footer_accueil:<front>'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Accueil',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_accueil:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_activits:node/2028.
  $menu_links['menu-menu-televie-footer_activits:node/2028'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'node/2028',
    'router_path' => 'node/%',
    'link_title' => 'Activités',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_activits:node/2028',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_agenda:node/2028.
  $menu_links['menu-menu-televie-footer_agenda:node/2028'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'node/2028',
    'router_path' => 'node/%',
    'link_title' => 'Agenda',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_agenda:node/2028',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_au-jour-le-jour:au-jour-le-jour.
  $menu_links['menu-menu-televie-footer_au-jour-le-jour:au-jour-le-jour'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'au-jour-le-jour',
    'router_path' => 'au-jour-le-jour',
    'link_title' => 'Au jour le jour',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_au-jour-le-jour:au-jour-le-jour',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_contactez-nous:node/2746.
  $menu_links['menu-menu-televie-footer_contactez-nous:node/2746'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'node/2746',
    'router_path' => 'node/%',
    'link_title' => 'Contactez-nous',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_contactez-nous:node/2746',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_informations-pdagogiques:node/2316.
  $menu_links['menu-menu-televie-footer_informations-pdagogiques:node/2316'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'node/2316',
    'router_path' => 'node/%',
    'link_title' => 'Informations pédagogiques',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_informations-pdagogiques:node/2316',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_infos-utiles:node/891.
  $menu_links['menu-menu-televie-footer_infos-utiles:node/891'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'node/891',
    'router_path' => 'node/%',
    'link_title' => 'Infos utiles',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_infos-utiles:node/891',
    ),
    'module' => 'menu',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_le-tlvie-son-histoire-ses-gains:node/2493.
  $menu_links['menu-menu-televie-footer_le-tlvie-son-histoire-ses-gains:node/2493'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'node/2493',
    'router_path' => 'node/%',
    'link_title' => 'Le Télévie, son histoire, ses gains',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_le-tlvie-son-histoire-ses-gains:node/2493',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_les-vidos-du-tlvie:node/2487.
  $menu_links['menu-menu-televie-footer_les-vidos-du-tlvie:node/2487'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'node/2487',
    'router_path' => 'node/%',
    'link_title' => 'Les vidéos du Télévie',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_les-vidos-du-tlvie:node/2487',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-menu-televie-footer_news:au-jour-le-jour.
  $menu_links['menu-menu-televie-footer_news:au-jour-le-jour'] = array(
    'menu_name' => 'menu-menu-televie-footer',
    'link_path' => 'au-jour-le-jour',
    'router_path' => 'au-jour-le-jour',
    'link_title' => 'News',
    'options' => array(
      'attributes' => array(),
      'item_attributes' => array(
        'id' => '',
        'class' => '',
        'style' => '',
      ),
      'identifier' => 'menu-menu-televie-footer_news:au-jour-le-jour',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'language' => 'und',
    'menu_links_customized' => 1,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('A propos du Télévie');
  t('Accueil');
  t('Activités');
  t('Agenda');
  t('Au jour le jour');
  t('Contactez-nous');
  t('Informations pédagogiques');
  t('Infos utiles');
  t('Le Télévie, son histoire, ses gains');
  t('Les vidéos du Télévie');
  t('News');

  return $menu_links;
}
